config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'articles#index'
  get '/about-us', to: 'home#about_us'
  resources :users do
    collection do
      get 'login', to: 'users#login_form'
      post 'login', to: 'users#login'
      post 'login_app', to: 'users#login_app', defaults: {format: :json}
      get 'logout', to: 'users#logout'
    end
  end
  resources :stories
  resources :events
  resources :event_notes
  resources :articles
  resources :downloads

  # mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user && user.admin?
      can :manage, :all
    else
      can [:edit, :update], [User] do |other_user|
        user && user.id == other_user.id
      end
      can [:read, :index], [Article, Event, Story, Download, User]
      can [:login_app, :login, :logout, :login_form, :new, :create], [User]
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :country
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/system/images/no-image.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  before_validation :shorten_teaser

  protected
    def shorten_teaser
      self.teaser = self.teaser.to_s[0..301]
    end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
  belongs_to :lower, class_name: 'User'
  belongs_to :higher, class_name: 'User'


  def self.flatten(conversations)
    flat_conversations = conversations.collection do |conversation|

    end
  end
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :users
  has_many :events
  has_many :stories
  has_many :articles
  has_many :downloads
end

app/models/download.rb
class Download < ApplicationRecord
  belongs_to :user
  has_attached_file :file
  validates_attachment_content_type :file, content_type: ["application/zip", "application/x-zipa", "application/pdf"]
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :country
  has_many :responses, class_name: 'EventNote', dependent: :destroy
end

app/models/event_note.rb
class EventNote < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  attr_accessor :to
  belongs_to :user
  belongs_to :conversation, touch: true

  after_create_commit { 
    conversation = self.conversation
    number_of_messages = Message.where(conversation_id: conversation.id).count
    conversation.assign_attributes(cache_message_count: number_of_messages, last_message_at: self.created_at)
    conversation.save!
    MessageBroadcastJob.perform_later conversation
  }

  before_validation :set_conversation
  protected
    def set_conversation
      conversation = User.find(self.user_id).conversation_with(@to)
      self.conversation_id = conversation.id
    end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  belongs_to :country
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :country
  has_many :downloads

  before_validation :reset_persistence_token, :if => :reset_persistence_token?

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "128x128#" }, default_url: "/system/images/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def admin?
    self.role == 'admin'
  end

  def conversation_with(other_id)
    if self.id > other_id
      lower_id, higher_id = other_id, self.id
    else
      lower_id, higher_id = self.id, other_id
    end

    Conversation.find_or_create_by!(lower_id: lower_id, higher_id: higher_id)
  end

  def self.conversations_of(user_id)
    Conversation.includes(:messages).where('lower_id = ? OR higher_id = ?', user_id, user_id)
  end

  def token
    Digest::MD5.hexdigest(self.id.to_s)
  end

  protected
    def reset_persistence_token?
      self.persistence_token.nil?
    end

    def reset_persistence_token
      self.persistence_token = self.id if self.id.present?
    end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  def other_user_in_conversation(me, lower, higher)
    if me == lower
      user_id = higher
    else
      # It means me == higher
      user_id = lower
    end

    User.find(user_id)
  end

  def is_selected(name)
    if controller_name == name
      "Navigation__Item--selected"
    else
      ""
    end
  end

  def article_with_teaser(article)
    # "#{article.teaser}\n\n#{article.body[0.150]}"
    article.teaser
  end
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/event_notes_helper.rb
module EventNotesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_call_to_action.html.haml
.CallToAction
  - if can?(:create, Article) && controller_name == 'articles' && action_name != 'new'
    %a.CallToAction__Icon.CallToAction__PostArticle{href: new_article_path, title: "Post an article"}
  - if can?(:create, Event) && controller_name == 'events' && action_name != 'new'
    %a.CallToAction__Icon.CallToAction__AddEvent{href: new_event_path, title: "Add en event"}
  - if can?(:create, Event) && controller_name == 'stories' && action_name != 'new'
    %a.CallToAction__Icon.CallToAction__ShareStory{href: new_story_path, title: "Share your story"}
  - if can?(:create, Download) && controller_name == 'downloads' && action_name != 'new'
    %a.CallToAction__Icon.CallToAction__UploadFile{href: new_download_path, title: "Upload a file"}
  -# %a.CallToAction.CallToAction__MakeDonation{href: new_donation_path, title: "Make a donation"}

app/views/layouts/_navigation.html.haml
.Navigation
  .Navigation__Wrapper
    .Navigation__Logo
      = link_to 'IMY320', root_path
    %ul.Navigation__List
      %li.Navigation__Item.Navigation__Effect{class: is_selected('articles')}
        = link_to 'News', articles_path
      %li.Navigation__Item.Navigation__Effect{class: is_selected('events')}
        = link_to 'Events', events_path
      %li.Navigation__Item.Navigation__Effect{class: is_selected('stories')}
        = link_to 'Stories', stories_path
      %li.Navigation__Item.Navigation__Effect{class: is_selected('downloads')}
        =link_to "Files", downloads_path
      %li.Navigation__Item.Navigation__Effect{class: is_selected('home')}
        = link_to "About Us", about_us_path
    %ul.Navigation__User
      -if current_user
        %li.Navigation__Item.Navigation__Item--no-hover
          %a{href: user_path(current_user)}
            %div.Navigation__UserName
              = current_user.name
            %div.Navigation__ProfilePictureWrapper
              %img.Navigation__ProfilePicture{src: current_user.avatar.url(:thumb), alt: "#{current_user.name}'s profile picture'"}
        %li.Navigation__Item.Navigation__Effect.Navigation__Item--button
          = link_to 'Logout', logout_users_path
      - else 
        %li.Navigation__Item.Navigation__Effect.Navigation__Item--button
          = link_to  'Register', new_user_path
        %li.Navigation__Item.Navigation__Effect.Navigation__Item--button
          = link_to 'Login', login_users_path

    .clear-fix

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Imy320
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .Container
      = render partial: 'layouts/call_to_action'
      = render partial: 'layouts/navigation'
      .Page__Left
        = yield
      .Page__Right
        Right Section